# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
  - job: A2

- stage: B
  jobs:
  - job: B1



