# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  global_variable: "global_variable" 

trigger:
- master

stages:
- stage: A
  jobs:
 
  - job: A1
    pool: Azure Pipelines
    variables:
     job_variable1: "job_variable1"
    steps:
    - bash: echo "Hello, world!"
      displayName: 'Run a one-line script'
    - bash: echo "##vso[task.setvariable variable=myOutputVar;isoutput=true]this is from job A"
      displayName: passOutput
  - job: A2
    pool: Azure Pipelines
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'

- stage: B
  jobs:
  - job: B1
    pool: Azure Pipelines
    steps:
      - bash: echo "Hello, world!""
        displayName: 'Run a one-line script'



